language: objective-c
osx_image: xcode8
before_install: rvm use 2.0
install: gem install slather
script: xcodebuild test -project LeanCloud.xcodeproj -scheme LeanCloud -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success: slather
